import os
MYSQL=os.environ.get("MYSQL", "")
ENVIRONTMENT = 'dev'
SECRET_KEY='Rx5634F0waUoh8ExHsDq6lGHFbT6u2AwxEXz9UqYIRZorsGV2J15p8LUxtOb9Qx1HqZnrtlMplNaFHkkIYJEVBE6eDgIfRiVh9su'
ALGORITHM='HS256'
ACCESS_TOKEN_EXPIRE_MINUTES=720
TZ='Asia/Jakarta'
MAIL_USERNAME="77f9dc002@smtp-brevo.com"
MAIL_PASSWORD="sGmcv6CT5kNIQPLd"
MAIL_FROM="mahrusrafi@gmail.com"
MAIL_PORT=587
MAIL_SERVER="smtp-relay.brevo.com"
MAIL_FROM_NAME="HRIS KU"
MAIL_TLS=False
MAIL_SSL=False
USE_CREDENTIALS=True
FE_DOMAIN='hris.com'